# This file is @generated by scripts/update_homebrew_formula.py.
class W < Formula
  desc "Experimental multi-repo wrapper for Worktrunk"
  homepage "https://github.com/prateek/w"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/prateek/w/releases/download/v0.1.0/w-v0.1.0-macos-ARM64.tar.gz"
      sha256 "78e3ebeec75701b12f1114ecf8302a2a9deb714c6217dba8b08e0afd44f84ddb"
    else
      url "https://github.com/prateek/w/releases/download/v0.1.0/w-v0.1.0-macos-X64.tar.gz"
      sha256 "5ad123afa52f1f6de133c2718812f639d226f964a41c077fb35beae93a5502fb"
    end
  end
  on_linux do
    if Hardware::CPU.arm?
      odie "No prebuilt Linux ARM64 artifacts are published for this release."
    end

    url "https://github.com/prateek/w/releases/download/v0.1.0/w-v0.1.0-linux-X64.tar.gz"
    sha256 "38a55e78be713bdf545eaa70242c90e2ff937a9b01338cffe9f48ddaee6c6bf3"
  end


  head do
    url "https://github.com/prateek/w.git", branch: "main"
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", "--locked", "--path", "crates/w", "--bin", "w", "--root", prefix
      system "cargo", "install", "--locked", "--path", "vendor/worktrunk", "--bin", "wt", "--root", prefix
      return
    end

    pkg_dir = Dir["w-*"].first
    if pkg_dir.nil?
      bin.install "w"
      bin.install "wt"
      return
    end

    bin.install "#{pkg_dir}/w"
    bin.install "#{pkg_dir}/wt"
  end

  test do
    assert_match "zsh", shell_output("#{bin}/w shell init zsh")
  end
end
